language: node_js
cache: # información ya configurada para el proyecto
  directories:
    - node_modules
    - ~/.npm

node_js: #version
  - '12'
git: # número de versiones (git) a guardar
  depth: 3

script: #script a ejecutar
  - yarn build
#Ahora vamos a lanzar notificaciones:  
notifications:
  email:
    recipients:
      - johny.jxc@gmail.com
      - xjohnyx@pm.me
    on_success: always #Cuando este funcione envia correo
    on_failure: always #Cuando este falle, envia correo


deploy:
  provider: pages
  #github pages
# configuración del deploy:
  skip_cleanup: true
  keep_history: true
  # creación de un token para la conexión
# entre Travis y GitHub:
  github_token: $GITHUB_TOKEN
  # directorio resultante de la compilación:
# xej: /bundle  /public ...etc
  local_dir: dist/
  target_branch: gh-pages
  # rama de publicación (sitio) de GitHub:

  commit-message: "Deploy del proyecto"
  on:
    branch: master